apiVersion: v1
kind: Pod
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
spec:
  containers:
    - name: gateway
      image: f2js/gateway:latest
      env:
        - name: "TOKEN_SECRET"
          value: ${TOKEN_SECRET}
      ports:
        - containerPort: 4000
